### PR TITLE
fixed issue#62

### LINKED ISSUE #62: Renderflex issue in the signup screen
### **Describe the bug:**
The signup screen is not compatible with small screen sizes 

### **To Reproduce:**
i will add padding at the bottom of the screen and make compatible with every screen size. Plz let me work on this issue

### **Screenshots:**
image

<hr/>
 plz let me work on this issue @ghackg11

### PR DESCRIPTION
**Pull request by anotherwebguy**
# Description:

i have fixed issue #62 renderflex issue in signup screen

Fixes #62 

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)

 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

# Screenshots / Video:
image

### CODE REVIEW

**Comment by anotherwebguy** [comment]
> # Description:
> i have fixed issue #62 renderflex issue in signup screen
> 
> Fixes #62
> 
> ## Type of change:
> * [x]  Bug fix (non-breaking change which fixes an issue)
> 
> # Checklist:
> * [x]  My code follows the style guidelines of this project.
> * [x]  I have performed a self-review of my own code.
> * [x]  My changes generate no new warnings.
> 
> # Screenshots / Video:
> image

plz review @ghackg11 @vaibhavarora102 @vilsi12 @Sameerkash @DARK-art108

**Comment by anotherwebguy** [comment]
Hey mentors and admin plz review my pr and add a label

**Comment by vaibhavarora102** [comment]
@anotherwebguy  we are looking into this, thanks for your patience

File: lib/components/signUp.dart [hunk 1]
```diff
@@ -114,7 +115,7 @@ class _SignUpScreenState extends State<SignUpScreen> {
                   ),
                 ),
                 SizedBox(
-                  height: 10.0,
+                  height: MediaQuery.of(context).size.height * 0.01,
```
Comment (sameeerkashyap) [inline lib/components/signUp.dart]: It'd be great if you created a helper class for MediaQuery instead of calling `MediaQuery.of(context)` every time. This makes the code too redundant.

File: lib/components/signUp.dart [hunk 2]
```diff
@@ -184,7 +185,7 @@ class _SignUpScreenState extends State<SignUpScreen> {
                   ),
                 ),
                 SizedBox(
-                  height: 5.0,
+                  height:  MediaQuery.of(context).size.height * 0.0005,
```
Comment (sameeerkashyap) [inline lib/components/signUp.dart]: Just using MediaQuery's height wouldn't work in a wider aspect ration phone, we'd have to use breakpoints to assign heights, checkout [DevicePreivew](https://pub.dev/packages/device_preview) to test your code with different screen sized.

**Review by sameeerkashyap — CHANGES_REQUESTED** [review]
Please take a look, it'd be best if this is made optimal like I've mentioned.

**Comment by anotherwebguy** [comment]
Made changes

**Review by sameeerkashyap — APPROVED** [review]
Looks okay for now, would require a utility helper to for long term
